RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :posts, except: [:new] do 
    resources :comments, only: [:new]
  end

  resources :comments, except: [:new]
end

RedditOnRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditOnRails/app/models/comment.rb
class Comment < ApplicationRecord

validates :content, :author_id, :post_id, presence: true

belongs_to :post
end

RedditOnRails/app/models/post.rb
class Post < ApplicationRecord
  

  validates :title, :sub_id, :author_id, presence: true
  
  belongs_to :user,
  foreign_key: :author_id,
  class_name: :User 

  belongs_to :sub,
  foreign_key: :sub_id,
  class_name: :Sub 

  has_many :comments

end

RedditOnRails/app/models/sub.rb
class Sub < ApplicationRecord

  validates :title, :description, :moderator_id, presence: true

  has_many :posts,
  foreign_key: :sub_id,
  class_name: :Post

  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: :User 





end

RedditOnRails/app/models/user.rb
class User < ApplicationRecord
validates :username, :session_token, presence: true, uniqueness: true
validates :password_digest, presence: true
validates :password, length:{minimum: 6}, allow_nil: true
attr_reader :password
after_initialize :ensure_session_token

has_many :subs,
foreign_key: :moderator_id,
class_name: :Sub 

has_many :posts,
foreign_key: :author_id,
class_name: :Post 

def self.find_by_credentials(username, password)
  @user = User.find_by(username: username)
  return nil if !@user
  return @user if @user.is_password?(password)
end

def password=(password)
  self.password_digest = BCrypt::Password.create(password)
  @password = password
end

def is_password?(password)
  BCrypt::Password.new(self.password_digest).is_password?(password)
end

def reset_session_token
  self.session_token = SecureRandom.urlsafe_base64
  self.save
  self.session_token
end

def ensure_session_token
  self.session_token ||= SecureRandom.urlsafe_base64
end


end

RedditOnRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in? 

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  
  end

  def login(user)
    session[:session_token] = user.reset_session_token
    @current_user = user 
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token 
    @current_user = nil 
    session[:session_token] = nil
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

end

RedditOnRails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  
  def new
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id 

    if @comment.save 
      redirect_to post_url(@comment.post_id)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

RedditOnRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_logged_in 

  def new
    @post = Post.new
    # @post.sub_id = params[:sub_id] 
    render :new
  end

  def create 
    @post = Post.new(post_params)
    @post.author_id = current_user.id 

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def index
    @posts = Post.all
    render :index
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to posts_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end
end

RedditOnRails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
    user = User.new
    render :new
  end

  def create
    user = User.find_by_credentials( 
      params[:user][:username],
      params[:user][:password]
    )

    if user 
      login(user)
      redirect_to subs_url #come back here to determine where we're going
    else  
      flash.now[:errors] = ['Invalid username or password.']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end


end                            

RedditOnRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_logged_in 

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all 
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end
  
  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

RedditOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end


  def create
    @user = User.new(user_params)

    if @user.save 
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditOnRails/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditOnRails/app/helpers/comments_helper.rb
module CommentsHelper
end

RedditOnRails/app/helpers/posts_helper.rb
module PostsHelper
end

RedditOnRails/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditOnRails/app/helpers/subs_helper.rb
module SubsHelper
end

RedditOnRails/app/helpers/users_helper.rb
module UsersHelper
end

RedditOnRails/app/views/comments/new.html.erb
<h1>New Comment</h1>

<form action="<%=comments_url%>" method="POST">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<input type="hidden" name="comment[post_id]"  value="<%=@comment.post_id%>">


<label>Content:
  <input type="text" name="comment[content]" value="">
</label>

<input type="submit" value="Create New Comment">
</form>

RedditOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <% if logged_in? %>
    Hello <%= current_user.username %>!
    <form action="<%=session_url%>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <input type="hidden" name="_method" value="DELETE"> 
      <input type="Submit" value="Sign Out">
    </form>
  <% else %>
  <a href="<%=new_session_url%>">Sign In</a>
  <br>
  <a href="<%=new_user_url%>">Sign Up</a>
      
  <% end %>
  <br>
    
    <% if flash[:errors] %>
      <%= flash[:errors].join(', ') %>
    <% end %>
    <%= yield %>
  </body>
</html>

RedditOnRails/app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%=posts_url%>" method="POST">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<input type="hidden" name="post[sub_id]"  value="<%=params[:sub_id]%>">


<label>Title:
  <input type="text" name="post[title]" value="">
</label>

<label> URL:
<input type="text" name="post[url]" value="">
</label>

<label> Content:
<textarea name="post[content]">Enter text here...</textarea>
</label>

<input type="submit" value="Create New Post">
</form>

<a href="<%=subs_url%>">Go back to all subs.</a>

RedditOnRails/app/views/posts/show.html.erb
<%= @post.title%>
<br>
<%= @post.content%>
<br>
Authored by: <%= @post.user.username %>

 <form action="<%=post_url(@post)%>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <input type="hidden" name="_method" value="DELETE"> 
      <input type="Submit" value="Delete Post">
</form>

<% @post.comments.each do |comment| %>
<ul><li>
<%= comment.content %>
</li></ul>
<% end %>
<a href="<%= new_post_comment_url(@post) %>">New Comment</a>
<a href="<%=subs_url%>">Go back to all subs.</a>

RedditOnRails/app/views/subs/index.html.erb
<h1> Here are all our subs. </h1> 

<ul><% @subs.each do |sub| %>
    <li>
        <a href="<%=sub_url(sub)%>"><%= sub.title %></a>
    </li>
  <% end %>
</ul>

<a href="<%=new_sub_url%>">New Sub</a>

RedditOnRails/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%=subs_url%>" method="POST">
 <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

<label>Title:
  <input type="text" name="sub[title]" value="">
</label>

<label> Description:
<textarea name="sub[description]">Enter text here...</textarea>
</label>

<input type="submit" value="Create New Sub">
</form>
<!-- >
<label>Description:
  <input type="text" name="subs[description]" value="">
</label>

<input type="submit" value="Create New Sub">

</form>

RedditOnRails/app/views/subs/show.html.erb
<%= @sub.title %>
<br>
<%= @sub.description %>
<br>
Authored by: <%= @sub.moderator.username %>


 <form action="<%=sub_url(@sub)%>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <input type="hidden" name="_method" value="DELETE"> 
      <input type="Submit" value="Delete Sub">
</form>


<a href="<%=subs_url%>">Go back to all subs.</a>
<a href="<%=new_sub_post_url(@sub)%>">New Post</a> 

<h1>Posts In This Sub </h1>

<ul><% @sub.posts.each do |post| %>
    <li>
        <a href="<%=post_url(post)%>"><%= post.title %></a>
    </li>
  <% end %>
</ul>

RedditOnRails/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=users_url%>" method="POST">
 <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

<label>Username:
  <input type="text" name="user[username]" value="">
</label>


<label>Password:
  <input type="password" name="user[password]" value="">
</label>

<input type="submit" value="Sign Up">

</form>